<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PLPSOFT.ERP.SaaS.Modules.Promotions.Infrastructure\PLPSOFT.ERP.SaaS.Modules.Promotions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
